version: '3.9'
services:
  rental:
    container_name: rental
    hostname: rental
    image: rental
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - server.port=8081
      - server.servlet.context-path=/rental
      - spring.mvc.pathmatch.matching-strategy=ant_path_matcher
      - mongodb.database.table=rental
      - mongodb.connection.string=mongodb://mongodb_container:27017/
      - spring.profiles.active=localdev
    restart: on-failure
    depends_on:
      - mongodb_container
    networks:
      - rental-network

  mongo-seed:
    hostname: mongo-seed
    container_name: mongo-seed
    image: mongo-seed
    build:
      context: ./test-data
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb_container
    networks:
      - rental-network

  mongodb_container:
    hostname: mongodb_container
    container_name: mongodb_container
    image: mongo:6.0.3
    restart: always
    ports:
      - 27017:27017
    networks:
      - rental-network

networks:
  rental-network:
    name: rental-network