version: '3.9'
services:
  mongodb_container:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - rental-db:/data/db

volumes:
  rental-db:
    name: rental-db

networks:
  rental-network:
    name: rental-network