version: '3.9'
services:
  mongodb_container:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - rental-db:/data/db
    networks:
      - rental-network

volumes:
  rental-db:
    name: rental-db
  cache:
    name: cache

networks:
  rental-network:
    name: rental-network