version: '3.9'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data/cache
    networks:
      - rental-network

  mongodb_container:
    image: mongo:6.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - rental-db:/data/db
    networks:
      - rental-network

volumes:
  rental-db:
    name: rental-db

networks:
  rental-network:
    name: rental-network