version: '3.9'
services:
  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://mongodb_container:27017
    networks:
      - rental-network
    depends_on:
      - mongodb_container

  mongo-seed:
    build: ./test-data
    depends_on:
      - mongodb_container
    networks:
      - rental-network

  mongodb_container:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - rental-db:/data/db
    networks:
      - rental-network

volumes:
  rental-db:
    name: rental-db

networks:
  rental-network:
    name: rental-network